# Use postgres/example user/password credentials
version: '3.9'

networks:
  kommubil:

services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - kommubil

  backend:
    build:
      context: backend-aggr/backend
      dockerfile: Dockerfile
    environment:
      - spring_profiles_active=prod
    ports:
      - "8082:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - kommubil

  db:
    image:
      postgis/postgis:14-3.1-alpine
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: kommubil
      POSTGRES_USER: kommubil
    ports:
      - "5432:5432"
    networks:
      - kommubil

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - kommubil
    depends_on:
      - db
